### ISSUE TITLE
Provide node module api

### ISSUE THREAD

**Issue by stefanjudis** [egoist/imgcat#1]
Heyo... Just came around and would love to bring this new iterm feature into our build process and delight the other iterm users. :)

Do you have any plans on providing a node api so that a can directly call it in a script?

Thanks. :)

**Comment by egoist** [comment]
Yes, I would try to provide a node api, and PRs are welcome.

Currently a workaround is using `child_process` to call `./node_modules/imgcat/imgcat` from your module 😅

**Comment by egoist** [comment]
I've added a node.js api 😁 https://github.com/egoist/imgcat#usage

**Comment by stefanjudis** [comment]
Sweeet!

Thanks. :+1:
