### ISSUE TITLE
Auto Detect Iterm 2.9

### ISSUE THREAD

**Issue by stefanjudis** [egoist/imgcat#2]
Heyo...

Thanks for bringing in the node api so quickly.

Next question I'd have - what about auto detecting iterm 2.9+. As it is required it might make sense to bring in this check into the module itself?

Thanks.

I'm thinking of something like this:

```
imgcat('foo.jpg', (err, img) => {
    console.log(err) // [Error] "Sorry this works only on Iterm 2.9+"
})
```

**Comment by egoist** [comment]
I came up with an idea to achieve this, parse `/Applications/iTerm.app/Contents/Info.plist` to get the iTerm version.

Do you have any better idea?

**Comment by stefanjudis** [comment]
Something like this might work?

https://github.com/arthurvr/is-iterm/blob/master/index.js#L2

**Comment by egoist** [comment]
Yes, but it can only detect if it is iTerm, not the version.

**Comment by stefanjudis** [comment]
Just looking into it... Exposing iterm version in the shell itself shouldn't be that uncommon or?

**Comment by stefanjudis** [comment]
Hmm... okay - doesn't look like they're exposing any version information. :(
Seems like parsing `Info.plist` seems to be the way to go here...

**Comment by egoist** [comment]
Ok, I will make an npm module to do this.

I might remove the `callback mode` api too, since I think `Promise` and `.sync` are enough 😂

**Comment by stefanjudis** [comment]
Sounds good! :+1:

**Comment by egoist** [comment]
Module published as [`iterm-version`](https://github.com/egoist/iterm-version) and `imgcat` updated! 🎉

**Comment by egoist** [comment]
Now I find https://github.com/sindresorhus/term-img 's code is better 😅

**Comment by egoist** [comment]
Since https://github.com/sindresorhus/term-img is really good, I just turned `imgcat` 2.0 into a wrapper of that, now it can display image from url too.
