### ISSUE TITLE
Installing errors

### ISSUE THREAD

**Issue by Luckyfella73** [egoist/imgcat#3]
hi,

trying to install this npm module I get this output in terminal:

`$ npm install --save imgcat`

`npm WARN saveError ENOENT: no such file or directory, open '/Users/myUser/package.json`
`npm WARN enoent ENOENT: no such file or directory, open '/Users/myUser/package.json`
`npm WARN myUser No description`
`npm WARN myUser No repository field.`
`npm WARN myUser No README data`
`npm WARN myUser No license field.`

I have installed quite a few npm modules up to now without having this issue.

Any idea what I might do wrong?

**Comment by egoist** [comment]
Sorry for this, this commit fixed it https://github.com/egoist/imgcat/commit/c40136e18fbb374145c0767264d04f0bd5a59311
